services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: balance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
volumes:
  postgres: {}